spring.application.name=project
spring.data.mongodb.uri=mongodb+srv://surya:Surya2831@cluster0.c0130.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=projects
server.port=${PORT:8080}